chore: setup linkinator for custom applications
commercetools/merchant-center-application-kit pull request #1768
Opened 2020-09-29 13:22 UTC by davifantasia

#### Summary

#### Description

2020-09-29 13:27 UTC, emmenko requested changes
Thanks. Can you move it to the `website` folder only though?
It does not need to run in the main repo.

2020-09-29 13:27 UTC, emmenko commented on package.json
> +    "postbuild": "yarn check-links",
This should only be used as post build of the website.

```suggestion
    "postbuild:website": "yarn check-links",
```

2020-09-29 13:27 UTC, emmenko commented on package.json
> +    "check-links": "npx linkinator ./website/public/custom-applications/public",
```suggestion
    "check-links": "npx linkinator ./website/public/custom-applications",
```

2020-09-29 13:27 UTC, emmenko commented on package.json
> +    "postbuild": "yarn check-links",
Better to include it in the postbuild hook of the website package

2020-09-29 14:15 UTC, emmenko commented on website/linkinator.config.json
> +    ".(json|js|png|jpg|svg|css)(\\?(.*)+)?$",
I included this rule to exclude check for static assets (which are handled by Gatsby anyway).

2020-09-29 15:03 UTC, adnasa commented
This came out of nowhere for me.
What's beneficial with linkinator?

2020-09-29 15:07 UTC, emmenko commented
It's what we use in the docs websites to check that links are correct.

2020-09-30 08:29 UTC, emmenko approved these changes

2020-09-30 08:29 UTC, merged