PAN-1031/DCY-123: Menu item and submenu of currently loaded application active in navbar
commercetools/merchant-center-application-kit pull request #2358
Opened 2021-09-10 14:18 UTC by ByronDWall

Summary

Issue: When a user opens a link from another MC App, the left menu submenu is not expanded upon initial load. From a users perspective though, there should be no difference in left menu behavior compared to when navigating between pages within an app (where the submenu remains open)

Suggestion: By default, have the submenu open when an app is opened so it works similar to when navigating between pages inside an app.
Description

This PR uses the isMainMenuRouteActive method in ApplicationMenu component in navbar.tsx to ascertain whether the currently loaded route matches the menu item, and sets the menu item to active and the submenus to be visible if the current route matches the menu item's url.
Tests

[x] unit tests - still need to be written, which is why this is a draft PR.
[x] integration tests - still need to be written, which is why this is a draft PR.
Browser Compat

[] - firefox
[] - chrome
[] - safari

closes #2352

2021-09-13 16:45 UTC, ByronDWall commented on cypress/integration/template-starter/channels.js
> +    });
The e2e test output has changed, but the output as it now stands (expanding the menu and activating the current menu item if the screen width is greater than 1024px) has been approved by UX, so I believe the chages in these two tests should be accepted.

2021-09-15 15:07 UTC, jmcreasman approved these changes
Looks good and makes sense to me!

2021-09-21 15:09 UTC, emmenko requested changes
Thanks for looking into it. I think I understand the point and I would agree with that.

However, I noticed from the VRT that the navbar opens when it's supposed to be collapsed. We should respect that, and expand the submenu only when the navbar is in an expanded state. Can you check that please?

Also FYI, we do have a "task" to refactor the navbar at some point with an improved UX (#1884 ).

2021-09-21 15:22 UTC, ByronDWall commented
> However, I noticed from the VRT that the navbar opens when it's supposed to be collapsed. We should respect that, and expand the submenu only when the navbar is in an expanded state. Can you check that please?

I was unclear whether it would be best to force it into an expanded state or keep it closed based on the UX spec.  Thanks for the clarification, I will update that shortly.

2021-09-29 15:40 UTC, emmenko approved these changes
@ByronDWall I pushed a bunch of commits to clean things up a bit. From my side this should be good to go now.
Thanks again for the pushing this 👌

2021-09-29 15:54 UTC, ByronDWall commented
> @ByronDWall I pushed a bunch of commits to clean things up a bit. From my side this should be good to go now. Thanks again for the pushing this 👌

Thank you for the cleanup, should I go through and approve the e2e test changes, or leave that to you?

2021-09-29 15:56 UTC, merged