refactor: remove support for updating application Id
commercetools/merchant-center-application-kit pull request #2585
Opened 2022-05-04 11:01 UTC by Rhotimee

#### Summary
Remove support for updating application Id in the custom-application file. 

Fixes #2560

2022-05-04 12:50 UTC, emmenko requested changes
Thanks, I think it makes things simpler to drop this.

However, we need to also update the messages of the CLI to instruct the user to put the ID into the config.

2022-05-05 11:32 UTC, emmenko reviewed
Thanks, just some wording improvements otherwise 👌

2022-05-05 11:32 UTC, emmenko commented on website/src/content/api-reference/cli.mdx
> +Additionally, after creating a Custom Application using the `config:sync` command, you should add the [Custom Application ID](/api-reference/application-config#envproductionapplicationid) generated t
```suggestion
Additionally, after creating a new Custom Application using the `config:sync` command, you must add the generated [Custom Application ID](/api-reference/application-config#envproductionapplicationid) to the application config file, following the instructions in the terminal.
```

2022-05-05 13:13 UTC, emmenko approved these changes
💯

2022-05-05 14:10 UTC, CarlosCortizasCT approved these changes
💯

2022-05-05 14:16 UTC, merged