refactor(main-pages): remove margin in form control
commercetools/merchant-center-application-kit pull request #2813
Opened 2022-09-19 12:59 UTC by Rhotimee

#### Summary
Remove unnecessary space from form control making the layout more compact

2022-09-19 13:59 UTC, emmenko commented
Could you provide some screenshots (before/after) to have a better idea of what exactly changed? Thanks

2022-09-19 14:02 UTC, Rhotimee commented
> Could you provide some screenshots (before/after) to have a better idea of what exactly changed? Thanks

Updated.

2022-09-19 14:18 UTC, emmenko commented
Wait a second, in the detail page we also have the form controls in a separate row

<img width="735" alt="image" src="https://user-images.githubusercontent.com/1110551/191039328-c4d9fb5b-d2f3-48f4-95ae-95c2fc340cd9.png">

What's the reason for changing this for the main page? I'm a bit confused now 🤔

2022-09-19 14:23 UTC, Rhotimee commented
> Wait a second, in the detail page we also have the form controls in a separate row
> What's the reason for changing this for the main page? I'm a bit confused now 🤔

This was changed in the [design](https://commercetools.invisionapp.com/spec/cl5s2aq2u0zbx01zefyvi86p3/select). 
@FilPob and I also talked about this.

2022-09-19 14:30 UTC, emmenko commented
We should be consistent with the detail pages, one way or the other. @FilPob Can you provide some guidance which way it should be?
Either way, it needs to be consistent.

2022-09-19 14:36 UTC, FilPob commented
> 

I thought the form controls would never be in a separate row which occupies the full width. It's like that in Modal pages and also in the tabular detail page... So I guess then it's rather the non-tabular detail page which should be adjusted. Otherwise the form controls take an unnecessary amount of vertical space.

2022-09-19 14:39 UTC, FilPob commented
Also in the tabular detail page we have form controls which are in the same line as the tabs 
<img width="1233" alt="image" src="https://user-images.githubusercontent.com/94548534/191043930-bd1b6de4-a5d5-43e0-b43a-1cee9511197f.png">

2022-09-19 14:43 UTC, emmenko commented
You mean to be like this?

<img width="817" alt="image" src="https://user-images.githubusercontent.com/1110551/191044905-e199af9c-495d-4590-91a6-c95812d06628.png">

2022-09-19 15:24 UTC, FilPob commented
Yes :)

2022-09-19 15:27 UTC, emmenko commented
Great, thanks.

@Rhotimee Can you take care of this? Thanks

2022-09-19 16:41 UTC, Rhotimee commented
> Great, thanks.
> 
> @Rhotimee Can you take care of this? Thanks

Sure 👍🏽

2022-09-21 08:09 UTC, emmenko requested changes
Hmm I don't think this is the right approach. Please also make sure the different layout combinations are correct. It might be that we also need to add one or two more VRTs.

I suppose all (form) pages (modal, detail, main) should have the same layout for the title, form controls, etc.
Maybe we should try to unify that logic.

2022-09-21 08:09 UTC, emmenko commented on packages/application-components/src/components/detail-pages/custom-form-detail-page/custom-form-detail-page.tsx
> +          <Spacings.Inline scale="l" justifyContent="space-between">
This is not correct. The `customTitleRow` should be in its own row.

<img width="711" alt="image" src="https://user-images.githubusercontent.com/1110551/191449877-d14dbef3-27ed-4bc0-a9b3-b116516b5fd6.png">

2023-03-29 08:22 UTC, closed without merging