Adding the release note for the main navigation
commercetools/merchant-center-application-kit pull request #3234
Opened 2023-09-26 10:16 UTC by chloe0592

Any help/suggestions with writing the release note for the new navigation would be much appreciated! 🍫

2023-09-26 11:24 UTC, Anshuman71 requested changes
Good job. Just a few suggestions.

2023-09-26 11:24 UTC, Anshuman71 commented on website/src/releases/2023-10/new-theme.mdx
> +As always, if you have questions or feedback, open a GitHub [discussion](https://github.com/commercetools/merchant-center-application-kit/discussions) or [issue](https://github.com/commercetools/merc
Hi @chloe0592, good work with the release. I've added the suggestion to streamline the terms used and align with the [release notes guidelines](https://commercetools.atlassian.net/wiki/spaces/DOCS/pages/105818548/Writing+release+notes). Please check if the intent is still intact.

```suggestion
---
date: 2023-10-06
title: Introduced the new main navigation menu for the Merchant Center
description: The new main navigation menu in the Merchant Center is now available.
type: announcement
topics:
  - Merchant Center
  - Development
---

The new main navigation menu brings a fresh look and enhanced functionality to help you navigate your application effortlessly. It provides a smoother and intuitive user experience in the Merchant Center. 

To use the new navigation menu, update the `ui-kit` and `app-kit` packages to the latest versions.

As always, if you have questions or feedback, open a GitHub [discussion](https://github.com/commercetools/merchant-center-application-kit/discussions) or [issue](https://github.com/commercetools/merchant-center-application-kit/issues).
```

2023-09-26 14:21 UTC, CarlosCortizasCT approved these changes
LGTM 👍 

Thanks!

2023-09-27 06:06 UTC, Anshuman71 approved these changes
Looks good to me!

2023-10-10 16:24 UTC, emmenko approved these changes

2023-10-12 07:40 UTC, emmenko approved these changes

2023-10-12 07:50 UTC, merged